a=3+2
print(a)
a=2**3+1
print(a)
a=2*3/6
print(a)
a=6/2*3
print(a)
a=2+3*6
print(a)
resultaat_berekening = (2*3)/(3+5)
print(resultaat_berekening)
resultaat_berekening=resultaat_berekening*2
print(resultaat_berekening)
resultaat_berekening=resultaat_berekening='abc'
print(resultaat_berekening)
resultaat_berekening=int('42')
print(resultaat_berekening)
a=0
a=a+1
a+=1
print(a)
